@startuml
skinparam classAttributeIconSize 0


class Tablero{

}

class ValidarVictoria{
    + validarAtaque(list, otraList): ResultadoCombate
}

class Continente{
    +paises: Pais
}

class Camino{}
class Dado{
    +obtenerNumeros(numeroDeTropas): list
}

class ResultadoCombate{
    +realizarAtaque(paisSalida, paisAAtacar, numeroDeTropas) : void
}

Tablero ---> "..*"Camino
Tablero *---> "5" Continente
Tablero ---> ValidarVictoria
Tablero <--> "1" Dado
ValidarVictoria <--->ResultadoCombate

@enduml
