@startuml
skinparam classAttributeIconSize 0

class Continente{



}

class Pais{
    +jugador: Jugador
    
    + noTengoTropas() : boolean;
    - conquistar() : void;
    + atacar(paisSalida, paisAAtacar, numeroDeTropas) : void
    + reducirTropas(numeroDeTropas) : void
}

class Pieza{}

interface Dibujo{}



Continente *---> "1..*"Pais
Pais -->Pieza
Pais -->Dibujo
Pais --> Tablero
@enduml