@startuml
skinparam classAttributeIconSize 0

class Juego {

}

class Partida{
        - cantidadTotalJugadores: int
        - cantidadJugadoresActivos: int
        - cantidadMaximaJugadoresPermitidos: int
        - juagres: Jugadores
        - objetivos: Objetivo
        - tarjetas: Tarjeta
        - ronda: int

        +atacar(paisSalida, paisAAtacar, numeroDeTropas): void
        +iniciarPartida():void
        -iniciarRonda():Jugador
}

class Jugador{
        +identfiicador: int 
        + color: str
        +objetivos: Objetivo
        +pais: Pais
        
        +atacar(partida, paisSalida, paisAAtacar, numeroDeTropas): void

}

class ValidadorAtaque{}

class Tablero{
        +continentes: Continente
} 


Juego ---> Partida
Partida --->"2..*" Jugador
Tablero ---> ValidadorAtaque
Partida ---> Tablero

@enduml