@startuml

class Continente{
    +nombre: String
    +gobernanteContinente: Jugador;

    + esGobernante(String colorGobernante): boolean



}

class Pais{
    +jugador: Jugador
    +nombre: String
    +int cantidadEjercito;
    +paisesLimitrofes: Paises

    + noTengoTropas() : boolean;
    - conquistar() : void;
    + atacar(paisSalida, paisAAtacar, numeroDeTropas) : void
    + reducirTropas(numeroDeTropas) : void
   + esGobernante(String colorGobernante): boolean:


}

Continente *---> "1..*"Pais

@enduml