@startuml
'https://plantuml.com/class-diagram


package "vista" {}
package "controlador"{}
package "modelo"{}
package "datosJuego" {}
package "exceptions" {}


"vista" --- "controlador"
"controlador" --- "modelo"
modelo --- "datosJuego"
modelo --- "exceptions"


@enduml