@startuml
skinparam classAttributeIconSize 0

class Juego {
       
}

class Partida{
        + cantidadJugadores: int
        +jugadoresMuertos: stack 
        +jugadoresVivos:list 
        +identificador:str 
        +objetivos: Objetivo

        +atacar(paisSalida, paisAAtacar, numeroDeTropas): void
}

class Jugador{
        +identfiicador: int 
        + color: str
        +objetivo: Objetivo 
        +pais: Pais
        
        +atacar(partida, paisSalida, paisAAtacar, numeroDeTropas): void

}

class ValidarAtaque{}

class Tablero{
        +continentes: Continente
} 


Juego ---> Partida
Partida --->"2..*" Jugador
Partida ---> ValidarAtaque
Partida ---> Tablero

@enduml