@startuml
skinparam classAttributeIconSize 0


class Tablero{

}

class Batalla{
    - int victoriaDefensor;
    - int victoriaAtacante;
    + obtenerPerdedorDeBatalla() : Pais;
    - determinarVictoriosoDeGuerra() : Pais;
    + obtenerVictorioso() : Pais;
}

class Continente{
    +paises: Pais
}

class Pais{
    +jugador: Jugador
}

class Dado{
    +obtenerNumeros(numeroDeTropas): list
}


Tablero *---> "5" Continente
Tablero ---> Batalla
Tablero <--> "1" Dado
Tablero ---> "--*" Pais



@enduml
