@startuml
skinparam classAttributeIconSize 0

interface ResultadoCombate{
    + realizarAtaque(paisSalida, paisAAtacar, numeroDeTropas) : void
}

class Victoria{
    +realizarAtaque(paisSalida, paisAAtacar, numeroDeTropas) : void
}
class Derrota{
    +realizarAtaque(paisSalida, paisAAtacar, numeroDeTropas) : void
}

ResultadoCombate <|--Victoria
ResultadoCombate <|-- Derrota
@enduml