@startuml


class RondaAtaque{

    +jugadorAtaca(Jugador jugadorAtacante, Pais atacante, Pais defensor, int cantidadTropas)
}

class RondaReagrupacion{
    +jugadorReagrupaTropas(Jugador jugadorActual, Pais salida, Pais llegada, int canidadTropas)
}
class RondaColocacion{
    +jugadorColoca(Pais unPais, int canidadTropas)
    +activarTarjeta(Tarjeta tarjeta,Jugador jugadorActual)
}

@enduml