@startuml
TestCase->Batalla: obtenerVictoriosoDeguerra(Pais atacante, Pais defensor, int cant tropas)
activate Batalla
Batalla -> LanzadorDados: obtenerDadosAtacante(Pais atacante, int cant Tropas)
LanzadorDados->Batalla: dadosAtacante
Batalla -> LanzadorDados: obtenerDadosDefensor(Pais defensor)
LanzadorDados->Batalla: dadosDefensor

Batalla -> Batalla: obtenerPerdedorDeBatalla(GeneradorRandom dadosAtacante, GeneradorRandom dadosDefensor, Pais atacante, Pais defensor)
activate Batalla
Batalla -> Batalla: agregarVictoriaAtacante()
Batalla-> paisPerdedor: reducirEjercito()
deactivate Batalla
Batalla->Batalla: determinarVictoriosoDeGuerra(paisAtacante,(Pais defensor)
Batalla->TestCase: pais victorioso
@enduml
